/* Generated by AN DISI Unibo */ 
package it.unibo.rover;
import it.unibo.qactors.PlanRepeat;
import it.unibo.qactors.QActorContext;
import it.unibo.qactors.StateExecMessage;
import it.unibo.qactors.QActorUtils;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.action.AsynchActionResult;
import it.unibo.qactors.action.IActorAction;
import it.unibo.qactors.action.IActorAction.ActionExecMode;
import it.unibo.qactors.action.IMsgQueue;
import it.unibo.qactors.akka.QActor;
import it.unibo.qactors.StateFun;
import java.util.Stack;
import java.util.Hashtable;
import java.util.concurrent.Callable;
import alice.tuprolog.Struct;
import alice.tuprolog.Term;
import it.unibo.qactors.action.ActorTimedAction;
public abstract class AbstractRover extends QActor { 
	protected AsynchActionResult aar = null;
	protected boolean actionResult = true;
	protected alice.tuprolog.SolveInfo sol;
	protected String planFilePath    = null;
	protected String terminationEvId = "default";
	protected String parg="";
	protected boolean bres=false;
	protected IActorAction action;
	 
	
		protected static IOutputEnvView setTheEnv(IOutputEnvView outEnvView ){
			return outEnvView;
		}
		public AbstractRover(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
			super(actorId, myCtx,  
			"./srcMore/it/unibo/rover/WorldTheory.pl",
			setTheEnv( outEnvView )  , "init");
			this.planFilePath = "./srcMore/it/unibo/rover/plans.txt";
	  	}
		@Override
		protected void doJob() throws Exception {
			String name  = getName().replace("_ctrl", "");
			mysupport = (IMsgQueue) QActorUtils.getQActor( name ); 
			initStateTable(); 
	 		initSensorSystem();
	 		history.push(stateTab.get( "init" ));
	  	 	autoSendStateExecMsg();
	  		//QActorContext.terminateQActorSystem(this);//todo
		} 	
		/* 
		* ------------------------------------------------------------
		* PLANS
		* ------------------------------------------------------------
		*/    
	    //genAkkaMshHandleStructure
	    protected void initStateTable(){  	
	    	stateTab.put("handleToutBuiltIn",handleToutBuiltIn);
	    	stateTab.put("init",init);
	    	stateTab.put("handleCommands",handleCommands);
	    	stateTab.put("connectToUnity",connectToUnity);
	    	stateTab.put("execMove",execMove);
	    	stateTab.put("handleTout",handleTout);
	    	stateTab.put("handleAlarm",handleAlarm);
	    	stateTab.put("endOfMove",endOfMove);
	    }
	    StateFun handleToutBuiltIn = () -> {	
	    	try{	
	    		PlanRepeat pr = PlanRepeat.setUp("handleTout",-1);
	    		String myselfName = "handleToutBuiltIn";  
	    		println( "rover tout : stops");  
	    		repeatPlanNoTransition(pr,myselfName,"application_"+myselfName,false,false);
	    	}catch(Exception e_handleToutBuiltIn){  
	    		println( getName() + " plan=handleToutBuiltIn WARNING:" + e_handleToutBuiltIn.getMessage() );
	    		QActorContext.terminateQActorSystem(this); 
	    	}
	    };//handleToutBuiltIn
	    
	    StateFun init = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("init",-1);
	    	String myselfName = "init";  
	    	temporaryStr = "\"Rover started!\"";
	    	println( temporaryStr );  
	    	//switchTo handleCommands
	        switchToPlanAsNextState(pr, myselfName, "rover_"+myselfName, 
	              "handleCommands",false, false, null); 
	    }catch(Exception e_init){  
	    	 println( getName() + " plan=init WARNING:" + e_init.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//init
	    
	    StateFun handleCommands = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp(getName()+"_handleCommands",0);
	     pr.incNumIter(); 	
	    	String myselfName = "handleCommands";  
	    	//bbb
	     msgTransition( pr,myselfName,"rover_"+myselfName,false,
	          new StateFun[]{stateTab.get("connectToUnity"), stateTab.get("execMove"), stateTab.get("handleAlarm") }, 
	          new String[]{"true","E","unityAddr", "true","M","moveRover", "true","E","alarm" },
	          60000, "handleTout" );//msgTransition
	    }catch(Exception e_handleCommands){  
	    	 println( getName() + " plan=handleCommands WARNING:" + e_handleCommands.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//handleCommands
	    
	    StateFun connectToUnity = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("connectToUnity",-1);
	    	String myselfName = "connectToUnity";  
	    	memoCurrentEvent( false );
	    	if( (guardVars = QActorUtils.evalTheGuard(this, " !?unityOn" )) != null ){
	    	temporaryStr = "\"Unity is already connected\"";
	    	temporaryStr = QActorUtils.substituteVars(guardVars,temporaryStr);
	    	println( temporaryStr );  
	    	}
	    	else{ {//actionseq
	    	//onEvent 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("unityAddr(X)");
	    	if( currentEvent != null && currentEvent.getEventId().equals("unityAddr") && 
	    		pengine.unify(curT, Term.createTerm("unityAddr(X)")) && 
	    		pengine.unify(curT, Term.createTerm( currentEvent.getMsg() ) )){ 
	    			String parg = "X";
	    			/* ConnectToUnity */
	    			parg =  updateVars( Term.createTerm("unityAddr(X)"), 
	    			                    Term.createTerm("unityAddr(X)"), 
	    				    		  	Term.createTerm(currentEvent.getMsg()), parg);
	    			if( parg != null ) initUnityConnection( parg );
	    	}
	    	parg = "createSimulatedActor"; 
	    	actorOpExecute(parg, false);	//OCT17		 
	    	temporaryStr = "unityOn";
	    	addRule( temporaryStr );  
	    	};//actionseq
	    	}
	    	repeatPlanNoTransition(pr,myselfName,"rover_"+myselfName,false,true);
	    }catch(Exception e_connectToUnity){  
	    	 println( getName() + " plan=connectToUnity WARNING:" + e_connectToUnity.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//connectToUnity
	    
	    StateFun execMove = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("execMove",-1);
	    	String myselfName = "execMove";  
	    	//onMsg 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("cmd(move(\"forward\",SPEED,DURATION))");
	    	if( currentMessage != null && currentMessage.msgId().equals("moveRover") && 
	    		pengine.unify(curT, Term.createTerm("cmd(CMD)")) && 
	    		pengine.unify(curT, Term.createTerm( currentMessage.msgContent() ) )){ 
	    		//println("WARNING: variable substitution not yet fully implemented " ); 
	    		{//actionseq
	    		execUnity("rover","forward",0, 20,0); //rover: default namefor virtual robot		
	    		it.unibo.custom.path.register( myself ,"forward", guardVars.get("DURATION")  );
	    		};//actionseq
	    	}
	    	//onMsg 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("cmd(move(\"backward\",SPEED,DURATION))");
	    	if( currentMessage != null && currentMessage.msgId().equals("moveRover") && 
	    		pengine.unify(curT, Term.createTerm("cmd(CMD)")) && 
	    		pengine.unify(curT, Term.createTerm( currentMessage.msgContent() ) )){ 
	    		//println("WARNING: variable substitution not yet fully implemented " ); 
	    		{//actionseq
	    		execUnity("rover","backward",0, 20,0); //rover: default namefor virtual robot		
	    		it.unibo.custom.path.register( myself ,"backward", guardVars.get("DURATION")  );
	    		};//actionseq
	    	}
	    	//onMsg 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("cmd(move(\"stop\",SPEED,DURATION))");
	    	if( currentMessage != null && currentMessage.msgId().equals("moveRover") && 
	    		pengine.unify(curT, Term.createTerm("cmd(CMD)")) && 
	    		pengine.unify(curT, Term.createTerm( currentMessage.msgContent() ) )){ 
	    		//println("WARNING: variable substitution not yet fully implemented " ); 
	    		{//actionseq
	    		execUnity("rover","stop",750, 20,0); //rover: default namefor virtual robot		
	    		it.unibo.custom.path.register( myself ,"stop", guardVars.get("DURATION")  );
	    		};//actionseq
	    	}
	    	//onMsg 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("cmd(move(\"left\",SPEED,DURATION))");
	    	if( currentMessage != null && currentMessage.msgId().equals("moveRover") && 
	    		pengine.unify(curT, Term.createTerm("cmd(CMD)")) && 
	    		pengine.unify(curT, Term.createTerm( currentMessage.msgContent() ) )){ 
	    		//println("WARNING: variable substitution not yet fully implemented " ); 
	    		{//actionseq
	    		execUnity("rover","left",750, 20,0); //rover: default namefor virtual robot		
	    		it.unibo.custom.path.register( myself ,"left", guardVars.get("DURATION")  );
	    		};//actionseq
	    	}
	    	//onMsg 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("cmd(move(\"right\",SPEED,DURATION))");
	    	if( currentMessage != null && currentMessage.msgId().equals("moveRover") && 
	    		pengine.unify(curT, Term.createTerm("cmd(CMD)")) && 
	    		pengine.unify(curT, Term.createTerm( currentMessage.msgContent() ) )){ 
	    		//println("WARNING: variable substitution not yet fully implemented " ); 
	    		{//actionseq
	    		execUnity("rover","right",750, 20,0); //rover: default namefor virtual robot		
	    		it.unibo.custom.path.register( myself ,"right", guardVars.get("DURATION")  );
	    		};//actionseq
	    	}
	    	//onMsg 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("cmd(X)");
	    	if( currentMessage != null && currentMessage.msgId().equals("moveRover") && 
	    		pengine.unify(curT, Term.createTerm("cmd(CMD)")) && 
	    		pengine.unify(curT, Term.createTerm( currentMessage.msgContent() ) )){ 
	    		String parg = "X";
	    		/* Print */
	    		parg =  updateVars( Term.createTerm("cmd(CMD)"), 
	    		                    Term.createTerm("cmd(X)"), 
	    			    		  	Term.createTerm(currentMessage.msgContent()), parg);
	    		if( parg != null ) println( parg );
	    	}
	    	repeatPlanNoTransition(pr,myselfName,"rover_"+myselfName,false,true);
	    }catch(Exception e_execMove){  
	    	 println( getName() + " plan=execMove WARNING:" + e_execMove.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//execMove
	    
	    StateFun handleTout = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("handleTout",-1);
	    	String myselfName = "handleTout";  
	    	temporaryStr = "\"Time out\"";
	    	println( temporaryStr );  
	    	repeatPlanNoTransition(pr,myselfName,"rover_"+myselfName,false,true);
	    }catch(Exception e_handleTout){  
	    	 println( getName() + " plan=handleTout WARNING:" + e_handleTout.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//handleTout
	    
	    StateFun handleAlarm = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("handleAlarm",-1);
	    	String myselfName = "handleAlarm";  
	    	execUnity("rover","stop",0, 40,0); //rover: default namefor virtual robot		
	    	repeatPlanNoTransition(pr,myselfName,"rover_"+myselfName,false,true);
	    }catch(Exception e_handleAlarm){  
	    	 println( getName() + " plan=handleAlarm WARNING:" + e_handleAlarm.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//handleAlarm
	    
	    StateFun endOfMove = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("endOfMove",-1);
	    	String myselfName = "endOfMove";  
	    	temporaryStr = "\"endOfMove\"";
	    	println( temporaryStr );  
	    	repeatPlanNoTransition(pr,myselfName,"rover_"+myselfName,false,true);
	    }catch(Exception e_endOfMove){  
	    	 println( getName() + " plan=endOfMove WARNING:" + e_endOfMove.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//endOfMove
	    
	    protected void initSensorSystem(){
	    	//doing nothing in a QActor
	    }
	
	}
