/* Generated by AN DISI Unibo */ 
package it.unibo.rovermind;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Rovermind extends QActorMsgQueue{
	public MsgHandle_Rovermind(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
