/* Generated by AN DISI Unibo */ 
package it.unibo.sonarhandler;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Sonarhandler extends QActorMsgQueue{
	public MsgHandle_Sonarhandler(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
