/* Generated by AN DISI Unibo */ 
package it.unibo.console;
import it.unibo.qactors.PlanRepeat;
import it.unibo.qactors.QActorContext;
import it.unibo.qactors.StateExecMessage;
import it.unibo.qactors.QActorUtils;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.action.AsynchActionResult;
import it.unibo.qactors.action.IActorAction;
import it.unibo.qactors.action.IActorAction.ActionExecMode;
import it.unibo.qactors.action.IMsgQueue;
import it.unibo.qactors.akka.QActor;
import it.unibo.qactors.StateFun;
import java.util.Stack;
import java.util.Hashtable;
import java.util.concurrent.Callable;
import alice.tuprolog.Struct;
import alice.tuprolog.Term;
import it.unibo.qactors.action.ActorTimedAction;
public abstract class AbstractConsole extends QActor { 
	protected AsynchActionResult aar = null;
	protected boolean actionResult = true;
	protected alice.tuprolog.SolveInfo sol;
	protected String planFilePath    = null;
	protected String terminationEvId = "default";
	protected String parg="";
	protected boolean bres=false;
	protected IActorAction action;
	 
	
		protected static IOutputEnvView setTheEnv(IOutputEnvView outEnvView ){
			return outEnvView;
		}
		public AbstractConsole(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
			super(actorId, myCtx,  
			"./srcMore/it/unibo/console/WorldTheory.pl",
			setTheEnv( outEnvView )  , "init");
			this.planFilePath = "./srcMore/it/unibo/console/plans.txt";
	  	}
		@Override
		protected void doJob() throws Exception {
			String name  = getName().replace("_ctrl", "");
			mysupport = (IMsgQueue) QActorUtils.getQActor( name ); 
			initStateTable(); 
	 		initSensorSystem();
	 		history.push(stateTab.get( "init" ));
	  	 	autoSendStateExecMsg();
	  		//QActorContext.terminateQActorSystem(this);//todo
		} 	
		/* 
		* ------------------------------------------------------------
		* PLANS
		* ------------------------------------------------------------
		*/    
	    //genAkkaMshHandleStructure
	    protected void initStateTable(){  	
	    	stateTab.put("handleToutBuiltIn",handleToutBuiltIn);
	    	stateTab.put("init",init);
	    	stateTab.put("handleCommands",handleCommands);
	    	stateTab.put("handleCmd",handleCmd);
	    	stateTab.put("handleUserCmd",handleUserCmd);
	    	stateTab.put("handleInputCmd",handleInputCmd);
	    	stateTab.put("handleTout",handleTout);
	    }
	    StateFun handleToutBuiltIn = () -> {	
	    	try{	
	    		PlanRepeat pr = PlanRepeat.setUp("handleTout",-1);
	    		String myselfName = "handleToutBuiltIn";  
	    		println( "console tout : stops");  
	    		repeatPlanNoTransition(pr,myselfName,"application_"+myselfName,false,false);
	    	}catch(Exception e_handleToutBuiltIn){  
	    		println( getName() + " plan=handleToutBuiltIn WARNING:" + e_handleToutBuiltIn.getMessage() );
	    		QActorContext.terminateQActorSystem(this); 
	    	}
	    };//handleToutBuiltIn
	    
	    StateFun init = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("init",-1);
	    	String myselfName = "init";  
	    	//switchTo handleCommands
	        switchToPlanAsNextState(pr, myselfName, "console_"+myselfName, 
	              "handleCommands",false, false, null); 
	    }catch(Exception e_init){  
	    	 println( getName() + " plan=init WARNING:" + e_init.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//init
	    
	    StateFun handleCommands = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp(getName()+"_handleCommands",0);
	     pr.incNumIter(); 	
	    	String myselfName = "handleCommands";  
	    	//bbb
	     msgTransition( pr,myselfName,"console_"+myselfName,false,
	          new StateFun[]{stateTab.get("handleCmd"), stateTab.get("handleInputCmd"), stateTab.get("handleUserCmd") }, 
	          new String[]{"true","E","cmd", "true","E","inputcmd", "true","E","usercmd" },
	          60000, "handleTout" );//msgTransition
	    }catch(Exception e_handleCommands){  
	    	 println( getName() + " plan=handleCommands WARNING:" + e_handleCommands.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//handleCommands
	    
	    StateFun handleCmd = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("handleCmd",-1);
	    	String myselfName = "handleCmd";  
	    	//onEvent 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("cmd(start)");
	    	if( currentEvent != null && currentEvent.getEventId().equals("cmd") && 
	    		pengine.unify(curT, Term.createTerm("cmd(X)")) && 
	    		pengine.unify(curT, Term.createTerm( currentEvent.getMsg() ) )){ 
	    			String parg="cmd(start)";
	    			/* SendDispatch */
	    			parg = updateVars(Term.createTerm("cmd(X)"),  Term.createTerm("cmd(start)"), 
	    				    		  					Term.createTerm(currentEvent.getMsg()), parg);
	    			if( parg != null ) sendMsg("moveRover","rovermind", QActorContext.dispatch, parg ); 
	    	}
	    	repeatPlanNoTransition(pr,myselfName,"console_"+myselfName,false,true);
	    }catch(Exception e_handleCmd){  
	    	 println( getName() + " plan=handleCmd WARNING:" + e_handleCmd.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//handleCmd
	    
	    StateFun handleUserCmd = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("handleUserCmd",-1);
	    	String myselfName = "handleUserCmd";  
	    	//onEvent 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("usercmd(robotgui(w(X)))");
	    	if( currentEvent != null && currentEvent.getEventId().equals("usercmd") && 
	    		pengine.unify(curT, Term.createTerm("usercmd(robotgui(X))")) && 
	    		pengine.unify(curT, Term.createTerm( currentEvent.getMsg() ) )){ 
	    			String parg="cmd(move(\"forward\",40,0))";
	    			/* SendDispatch */
	    			parg = updateVars(Term.createTerm("usercmd(robotgui(X))"),  Term.createTerm("usercmd(robotgui(w(X)))"), 
	    				    		  					Term.createTerm(currentEvent.getMsg()), parg);
	    			if( parg != null ) sendMsg("moveRover","rover", QActorContext.dispatch, parg ); 
	    	}
	    	//onEvent 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("usercmd(robotgui(a(X)))");
	    	if( currentEvent != null && currentEvent.getEventId().equals("usercmd") && 
	    		pengine.unify(curT, Term.createTerm("usercmd(robotgui(X))")) && 
	    		pengine.unify(curT, Term.createTerm( currentEvent.getMsg() ) )){ 
	    			String parg="cmd(move(\"left\",50,750))";
	    			/* SendDispatch */
	    			parg = updateVars(Term.createTerm("usercmd(robotgui(X))"),  Term.createTerm("usercmd(robotgui(a(X)))"), 
	    				    		  					Term.createTerm(currentEvent.getMsg()), parg);
	    			if( parg != null ) sendMsg("moveRover","rover", QActorContext.dispatch, parg ); 
	    	}
	    	//onEvent 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("usercmd(robotgui(s(X)))");
	    	if( currentEvent != null && currentEvent.getEventId().equals("usercmd") && 
	    		pengine.unify(curT, Term.createTerm("usercmd(robotgui(X))")) && 
	    		pengine.unify(curT, Term.createTerm( currentEvent.getMsg() ) )){ 
	    			String parg="cmd(move(\"backward\",40,0))";
	    			/* SendDispatch */
	    			parg = updateVars(Term.createTerm("usercmd(robotgui(X))"),  Term.createTerm("usercmd(robotgui(s(X)))"), 
	    				    		  					Term.createTerm(currentEvent.getMsg()), parg);
	    			if( parg != null ) sendMsg("moveRover","rover", QActorContext.dispatch, parg ); 
	    	}
	    	//onEvent 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("usercmd(robotgui(d(X)))");
	    	if( currentEvent != null && currentEvent.getEventId().equals("usercmd") && 
	    		pengine.unify(curT, Term.createTerm("usercmd(robotgui(X))")) && 
	    		pengine.unify(curT, Term.createTerm( currentEvent.getMsg() ) )){ 
	    			String parg="cmd(move(\"right\",50,750))";
	    			/* SendDispatch */
	    			parg = updateVars(Term.createTerm("usercmd(robotgui(X))"),  Term.createTerm("usercmd(robotgui(d(X)))"), 
	    				    		  					Term.createTerm(currentEvent.getMsg()), parg);
	    			if( parg != null ) sendMsg("moveRover","rover", QActorContext.dispatch, parg ); 
	    	}
	    	//onEvent 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("usercmd(robotgui(h(X)))");
	    	if( currentEvent != null && currentEvent.getEventId().equals("usercmd") && 
	    		pengine.unify(curT, Term.createTerm("usercmd(robotgui(X))")) && 
	    		pengine.unify(curT, Term.createTerm( currentEvent.getMsg() ) )){ 
	    			String parg="cmd(move(\"stop\",40,0))";
	    			/* SendDispatch */
	    			parg = updateVars(Term.createTerm("usercmd(robotgui(X))"),  Term.createTerm("usercmd(robotgui(h(X)))"), 
	    				    		  					Term.createTerm(currentEvent.getMsg()), parg);
	    			if( parg != null ) sendMsg("moveRover","rover", QActorContext.dispatch, parg ); 
	    	}
	    	//onEvent 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("usercmd(robotgui(X))");
	    	if( currentEvent != null && currentEvent.getEventId().equals("usercmd") && 
	    		pengine.unify(curT, Term.createTerm("usercmd(robotgui(X))")) && 
	    		pengine.unify(curT, Term.createTerm( currentEvent.getMsg() ) )){ 
	    			String parg = "X";
	    			/* Print */
	    			parg =  updateVars( Term.createTerm("usercmd(robotgui(X))"), 
	    			                    Term.createTerm("usercmd(robotgui(X))"), 
	    				    		  	Term.createTerm(currentEvent.getMsg()), parg);
	    			if( parg != null ) println( parg );
	    	}
	    	repeatPlanNoTransition(pr,myselfName,"console_"+myselfName,false,true);
	    }catch(Exception e_handleUserCmd){  
	    	 println( getName() + " plan=handleUserCmd WARNING:" + e_handleUserCmd.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//handleUserCmd
	    
	    StateFun handleInputCmd = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("handleInputCmd",-1);
	    	String myselfName = "handleInputCmd";  
	    	//onEvent 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("usercmd(executeInput(connectToUnity(X)))");
	    	if( currentEvent != null && currentEvent.getEventId().equals("inputcmd") && 
	    		pengine.unify(curT, Term.createTerm("usercmd(executeInput(X))")) && 
	    		pengine.unify(curT, Term.createTerm( currentEvent.getMsg() ) )){ 
	    			String parg="unityAddr(X)";
	    			/* RaiseEvent */
	    			parg = updateVars(Term.createTerm("usercmd(executeInput(X))"),  Term.createTerm("usercmd(executeInput(connectToUnity(X)))"), 
	    				    		  					Term.createTerm(currentEvent.getMsg()), parg);
	    			if( parg != null ) emit( "unityAddr", parg );
	    	}
	    	//onEvent 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("usercmd(executeInput(setStartDistance(X)))");
	    	if( currentEvent != null && currentEvent.getEventId().equals("inputcmd") && 
	    		pengine.unify(curT, Term.createTerm("usercmd(executeInput(X))")) && 
	    		pengine.unify(curT, Term.createTerm( currentEvent.getMsg() ) )){ 
	    			String parg="startDistance(X)";
	    			/* RaiseEvent */
	    			parg = updateVars(Term.createTerm("usercmd(executeInput(X))"),  Term.createTerm("usercmd(executeInput(setStartDistance(X)))"), 
	    				    		  					Term.createTerm(currentEvent.getMsg()), parg);
	    			if( parg != null ) emit( "startDistance", parg );
	    	}
	    	//onEvent 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("usercmd(executeInput(move(X,Y,Z)))");
	    	if( currentEvent != null && currentEvent.getEventId().equals("inputcmd") && 
	    		pengine.unify(curT, Term.createTerm("usercmd(executeInput(X))")) && 
	    		pengine.unify(curT, Term.createTerm( currentEvent.getMsg() ) )){ 
	    			String parg="cmd(move(X,Y,Z))";
	    			/* SendDispatch */
	    			parg = updateVars(Term.createTerm("usercmd(executeInput(X))"),  Term.createTerm("usercmd(executeInput(move(X,Y,Z)))"), 
	    				    		  					Term.createTerm(currentEvent.getMsg()), parg);
	    			if( parg != null ) sendMsg("moveRover","rover", QActorContext.dispatch, parg ); 
	    	}
	    	//onEvent 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("usercmd(executeInput(X))");
	    	if( currentEvent != null && currentEvent.getEventId().equals("inputcmd") && 
	    		pengine.unify(curT, Term.createTerm("usercmd(executeInput(X))")) && 
	    		pengine.unify(curT, Term.createTerm( currentEvent.getMsg() ) )){ 
	    			String parg = "X";
	    			/* Print */
	    			parg =  updateVars( Term.createTerm("usercmd(executeInput(X))"), 
	    			                    Term.createTerm("usercmd(executeInput(X))"), 
	    				    		  	Term.createTerm(currentEvent.getMsg()), parg);
	    			if( parg != null ) println( parg );
	    	}
	    	repeatPlanNoTransition(pr,myselfName,"console_"+myselfName,false,true);
	    }catch(Exception e_handleInputCmd){  
	    	 println( getName() + " plan=handleInputCmd WARNING:" + e_handleInputCmd.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//handleInputCmd
	    
	    StateFun handleTout = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("handleTout",-1);
	    	String myselfName = "handleTout";  
	    	repeatPlanNoTransition(pr,myselfName,"console_"+myselfName,false,true);
	    }catch(Exception e_handleTout){  
	    	 println( getName() + " plan=handleTout WARNING:" + e_handleTout.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//handleTout
	    
	    protected void initSensorSystem(){
	    	//doing nothing in a QActor
	    }
	
	}
